services:
  - type: web
    name: ai-goal-predictor-bot
    env: node
    region: ohio  # يمكنك تغيير المنطقة حسب أقرب موقع لك
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /keep-alive
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: PORT
        value: 10000

    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1