services:
  - type: web
    name: ai-goal-predictor-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: ADMIN_ID
        fromSecret: ADMIN_ID
      - key: CHANNEL_ID
        fromSecret: CHANNEL_ID
      - key: CHANNEL_USERNAME
        fromSecret: CHANNEL_USERNAME
      - key: SUPPORT_USERNAME
        fromSecret: SUPPORT_USERNAME
      - key: FIREBASE_PRIVATE_KEY_ID
        fromSecret: FIREBASE_PRIVATE_KEY_ID
      - key: FIREBASE_PRIVATE_KEY
        fromSecret: FIREBASE_PRIVATE_KEY
      - key: FIREBASE_CLIENT_ID
        fromSecret: FIREBASE_CLIENT_ID
      - key: FIREBASE_CERT_URL
        fromSecret: FIREBASE_CERT_URL
      - key: IMGBB_API_KEY
        fromSecret: IMGBB_API_KEY