services:
  - type: web
    name: telegram-ai-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node bot.js"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: ADMIN_ID
        value: ${ADMIN_ID}
      - key: FIREBASE_PROJECT_ID
        value: ${FIREBASE_PROJECT_ID}
      - key: FIREBASE_CLIENT_EMAIL
        value: ${FIREBASE_CLIENT_EMAIL}
      - key: FIREBASE_PRIVATE_KEY
        value: ${FIREBASE_PRIVATE_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
      - key: IMGBB_API_KEY
        value: ${IMGBB_API_KEY}
      - key: PAYMENT_WEEK
        value: ${PAYMENT_WEEK}
      - key: PAYMENT_MONTH
        value: ${PAYMENT_MONTH}
      - key: PAYMENT_3MONTHS
        value: ${PAYMENT_3MONTHS}
      - key: PAYMENT_YEAR
        value: ${PAYMENT_YEAR}
      - key: PORT
        value: ${PORT}
